# Generated by Django 5.1.4 on 2025-01-02 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='enrollment_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 1, 2, 20, 14, 56, 389604, tzinfo=datetime.timezone.utc)),
        ),
    ]
