# Generated by Django 5.1.4 on 2025-01-02 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_enrolledcourse_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='enrollment_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 1, 2, 20, 16, 45, 259141, tzinfo=datetime.timezone.utc)),
        ),
    ]
