# Generated by Django 5.1.4 on 2025-01-02 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_enrolledcourse_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='enrollment_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 1, 2, 20, 33, 48, 180821, tzinfo=datetime.timezone.utc)),
        ),
    ]
