# Generated by Django 5.1.4 on 2025-01-02 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 1, 2, 14, 43, 3, 350626, tzinfo=datetime.timezone.utc)),
        ),
    ]
